[project]
name = "vmemu"

[target.vmemu]
type = "executable"

sources = ["src/**.cpp", "include/**.hpp"]
include-directories = ["include"]
link-libraries = ["vmprofiler", "unicorn", "argparse"]
compile-definitions = ["NOMINMAX"]
