[project]
name = "vmprofiler"

[target.vmprofiler]
type = "static"
compile-features = ["cxx_std_20"]

sources = ["src/**.cpp", "include/**.hpp"]
include-directories = ["include"]
link-libraries = ["Zydis", "linux-pe"]
compile-definitions = ["NOMINMAX"]
